local palette = require("monalisa.palette")
local config = require("monalisa.config")

---Get plugin highlight groups
---@return table<string, vim.api.keyset.highlight>
local function get()
  local p = palette
  local transparent = config.transparent

  local bg = transparent and p.none or p.bg
  local bg_float = transparent and p.none or p.lightBlack
  local bg_darker = transparent and p.none or p.bg

  return {
    -- Telescope
    TelescopeNormal = { fg = p.fg, bg = bg_float },
    TelescopeBorder = { fg = p.teal, bg = bg_float },
    TelescopeTitle = { fg = p.brightGreen, bold = true },
    TelescopePromptNormal = { fg = p.fg, bg = bg_float },
    TelescopePromptBorder = { fg = p.brightGreen, bg = bg_float },
    TelescopePromptTitle = { fg = p.brightGreen, bold = true },
    TelescopePromptPrefix = { fg = p.orange },
    TelescopePromptCounter = { fg = p.cmt },
    TelescopeResultsNormal = { fg = p.fg, bg = bg_float },
    TelescopeResultsBorder = { fg = p.teal, bg = bg_float },
    TelescopeResultsTitle = { fg = p.brightGreen, bold = true },
    TelescopePreviewNormal = { fg = p.fg, bg = bg_float },
    TelescopePreviewBorder = { fg = p.teal, bg = bg_float },
    TelescopePreviewTitle = { fg = p.brightGreen, bold = true },
    TelescopePreviewLine = { bg = p.selection },
    TelescopeSelection = { fg = p.fg, bg = p.selection },
    TelescopeSelectionCaret = { fg = p.orange, bg = p.selection },
    TelescopeMultiSelection = { fg = p.teal, bg = p.selection },
    TelescopeMultiIcon = { fg = p.teal },
    TelescopeMatching = { fg = p.orange, bold = true },

    -- FzfLua
    FzfLuaNormal = { fg = p.fg, bg = bg_float },
    FzfLuaBorder = { fg = p.teal, bg = bg_float },
    FzfLuaTitle = { fg = p.brightGreen, bold = true },
    FzfLuaCursor = { link = "Cursor" },
    FzfLuaSearch = { link = "IncSearch" },
    FzfLuaCursorLine = { bg = p.selection },
    FzfLuaCursorLineNr = { fg = p.fg, bg = p.selection },
    FzfLuaScrollFloatEmpty = { bg = p.lightBlack },
    FzfLuaScrollFloatFull = { bg = p.punc },
    FzfLuaPreviewNormal = { fg = p.fg, bg = bg_float },
    FzfLuaPreviewBorder = { fg = p.teal, bg = bg_float },
    FzfLuaPreviewTitle = { fg = p.brightGreen, bold = true },

    -- Neo-tree
    NeoTreeNormal = { fg = p.altfg, bg = bg },
    NeoTreeNormalNC = { fg = p.altfg, bg = bg },
    NeoTreeVertSplit = { fg = p.punc, bg = bg },
    NeoTreeWinSeparator = { fg = p.punc, bg = bg },
    NeoTreeEndOfBuffer = { fg = bg, bg = bg },
    NeoTreeSignColumn = { bg = bg },
    NeoTreeRootName = { fg = p.brightGreen, bold = true },
    NeoTreeGitAdded = { fg = p.green },
    NeoTreeGitDeleted = { fg = p.darkOrange },
    NeoTreeGitModified = { fg = p.punc },
    NeoTreeGitConflict = { fg = p.orange, bold = true },
    NeoTreeGitUntracked = { fg = p.teal },
    NeoTreeGitIgnored = { fg = p.cmt },
    NeoTreeGitRenamed = { fg = p.brightGreen },
    NeoTreeGitStaged = { fg = p.green },
    NeoTreeGitUnstaged = { fg = p.punc },
    NeoTreeIndentMarker = { fg = p.indentScope },
    NeoTreeExpander = { fg = p.altfg },
    NeoTreeFileIcon = { fg = p.altfg },
    NeoTreeFileName = { fg = p.altfg },
    NeoTreeFileNameOpened = { fg = p.fg },
    NeoTreeDirectoryIcon = { fg = p.brightGreen },
    NeoTreeDirectoryName = { fg = p.brightGreen },
    NeoTreeSymbolicLinkTarget = { fg = p.teal },
    NeoTreeDotfile = { fg = p.cmt },
    NeoTreeFloatBorder = { fg = p.teal, bg = bg_float },
    NeoTreeFloatNormal = { fg = p.fg, bg = bg_float },
    NeoTreeFloatTitle = { fg = p.brightGreen, bg = bg_float },
    NeoTreeTitleBar = { fg = p.brightGreen, bg = bg_float },
    NeoTreeCursorLine = { bg = p.selection },

    -- nvim-tree
    NvimTreeNormal = { fg = p.altfg, bg = bg },
    NvimTreeNormalNC = { fg = p.altfg, bg = bg },
    NvimTreeVertSplit = { fg = p.punc, bg = bg },
    NvimTreeWinSeparator = { fg = p.punc, bg = bg },
    NvimTreeEndOfBuffer = { fg = bg, bg = bg },
    NvimTreeRootFolder = { fg = p.brightGreen, bold = true },
    NvimTreeGitDirty = { fg = p.punc },
    NvimTreeGitNew = { fg = p.green },
    NvimTreeGitDeleted = { fg = p.darkOrange },
    NvimTreeGitMerge = { fg = p.orange },
    NvimTreeGitRenamed = { fg = p.brightGreen },
    NvimTreeGitStaged = { fg = p.green },
    NvimTreeGitIgnored = { fg = p.cmt },
    NvimTreeIndentMarker = { fg = p.indentScope },
    NvimTreeFolderIcon = { fg = p.brightGreen },
    NvimTreeFolderName = { fg = p.brightGreen },
    NvimTreeOpenedFolderName = { fg = p.brightGreen, bold = true },
    NvimTreeEmptyFolderName = { fg = p.cmt },
    NvimTreeSymlink = { fg = p.teal },
    NvimTreeSpecialFile = { fg = p.darkYellow },
    NvimTreeImageFile = { fg = p.orange },

    -- GitSigns
    GitSignsAdd = { fg = p.green },
    GitSignsChange = { fg = p.punc },
    GitSignsDelete = { fg = p.darkOrange },
    GitSignsAddNr = { fg = p.green },
    GitSignsChangeNr = { fg = p.punc },
    GitSignsDeleteNr = { fg = p.darkOrange },
    GitSignsAddLn = { bg = p.indentScope },
    GitSignsChangeLn = { bg = p.selection },
    GitSignsDeleteLn = { bg = p.lightBlack },
    GitSignsAddInline = { bg = p.indentScope },
    GitSignsChangeInline = { bg = p.selection },
    GitSignsDeleteInline = { bg = p.lightBlack },
    GitSignsCurrentLineBlame = { fg = p.cmt },
    GitSignsChangedelete = { fg = p.darkOrange },
    GitSignsTopdelete = { fg = p.darkOrange },
    GitSignsUntracked = { fg = p.cmt },
    GitSignsStagedAdd = { fg = p.teal },
    GitSignsStagedChange = { fg = p.cmt },
    GitSignsStagedDelete = { fg = p.crimson },

    -- Indent Blankline
    IndentBlanklineChar = { fg = p.indentScope, nocombine = true },
    IndentBlanklineSpaceChar = { fg = p.indentScope, nocombine = true },
    IndentBlanklineSpaceCharBlankline = { fg = p.indentScope, nocombine = true },
    IndentBlanklineContextChar = { fg = p.teal, nocombine = true },
    IndentBlanklineContextStart = { sp = p.teal, underline = true },
    IblIndent = { fg = p.indentScope, nocombine = true },
    IblWhitespace = { fg = p.indentScope, nocombine = true },
    IblScope = { fg = p.teal, nocombine = true },

    -- Which-key
    WhichKey = { fg = p.fg },
    WhichKeyGroup = { fg = p.brightGreen },
    WhichKeyDesc = { fg = p.green },
    WhichKeySeparator = { fg = p.cmt },
    WhichKeyFloat = { bg = bg_float },
    WhichKeyBorder = { fg = p.teal, bg = bg_float },
    WhichKeyValue = { fg = p.darkYellow },

    -- Lazy.nvim
    LazyButton = { fg = p.fg, bg = p.lightBlack },
    LazyButtonActive = { fg = p.bg, bg = p.brightGreen, bold = true },
    LazyComment = { fg = p.cmt },
    LazyCommit = { fg = p.green },
    LazyCommitIssue = { fg = p.orange },
    LazyCommitType = { fg = p.teal },
    LazyDimmed = { fg = p.cmt },
    LazyDir = { fg = p.teal },
    LazyH1 = { fg = p.bg, bg = p.brightGreen, bold = true },
    LazyH2 = { fg = p.brightGreen, bold = true },
    LazyNoCond = { fg = p.crimson },
    LazyNormal = { fg = p.fg, bg = bg_float },
    LazyProgressDone = { fg = p.brightGreen },
    LazyProgressTodo = { fg = p.cmt },
    LazyProp = { fg = p.cmt },
    LazyReasonCmd = { fg = p.darkYellow },
    LazyReasonEvent = { fg = p.orange },
    LazyReasonFt = { fg = p.teal },
    LazyReasonImport = { fg = p.green },
    LazyReasonKeys = { fg = p.brightGreen },
    LazyReasonPlugin = { fg = p.blueGreen },
    LazyReasonRuntime = { fg = p.altfg },
    LazyReasonSource = { fg = p.green },
    LazyReasonStart = { fg = p.darkYellow },
    LazySpecial = { fg = p.teal },
    LazyTaskError = { fg = p.crimson },
    LazyTaskOutput = { fg = p.fg },
    LazyUrl = { fg = p.teal, underline = true },
    LazyValue = { fg = p.green },

    -- Mason
    MasonHeader = { fg = p.bg, bg = p.brightGreen, bold = true },
    MasonHeaderSecondary = { fg = p.bg, bg = p.teal, bold = true },
    MasonHighlight = { fg = p.teal },
    MasonHighlightBlock = { fg = p.bg, bg = p.teal },
    MasonHighlightBlockBold = { fg = p.bg, bg = p.teal, bold = true },
    MasonHighlightBlockBoldSecondary = { fg = p.bg, bg = p.brightGreen, bold = true },
    MasonHighlightBlockSecondary = { fg = p.bg, bg = p.brightGreen },
    MasonHighlightSecondary = { fg = p.brightGreen },
    MasonMuted = { fg = p.cmt },
    MasonMutedBlock = { fg = p.bg, bg = p.cmt },
    MasonMutedBlockBold = { fg = p.bg, bg = p.cmt, bold = true },
    MasonNormal = { fg = p.fg, bg = bg_float },

    -- Cmp (nvim-cmp)
    CmpItemAbbr = { fg = p.fg },
    CmpItemAbbrDeprecated = { fg = p.cmt, strikethrough = true },
    CmpItemAbbrMatch = { fg = p.orange, bold = true },
    CmpItemAbbrMatchFuzzy = { fg = p.orange, bold = true },
    CmpItemKind = { fg = p.teal },
    CmpItemKindClass = { fg = p.darkOrange },
    CmpItemKindColor = { fg = p.orange },
    CmpItemKindConstant = { fg = p.crimson },
    CmpItemKindConstructor = { fg = p.darkOrange },
    CmpItemKindEnum = { fg = p.darkOrange },
    CmpItemKindEnumMember = { fg = p.crimson },
    CmpItemKindEvent = { fg = p.teal },
    CmpItemKindField = { fg = p.teal },
    CmpItemKindFile = { fg = p.green },
    CmpItemKindFolder = { fg = p.brightGreen },
    CmpItemKindFunction = { fg = p.green },
    CmpItemKindInterface = { fg = p.darkOrange },
    CmpItemKindKeyword = { fg = p.brightGreen },
    CmpItemKindMethod = { fg = p.green },
    CmpItemKindModule = { fg = p.blueGreen },
    CmpItemKindOperator = { fg = p.blueGreen },
    CmpItemKindProperty = { fg = p.teal },
    CmpItemKindReference = { fg = p.crimson },
    CmpItemKindSnippet = { fg = p.darkYellow },
    CmpItemKindStruct = { fg = p.darkOrange },
    CmpItemKindText = { fg = p.fg },
    CmpItemKindTypeParameter = { fg = p.darkOrange },
    CmpItemKindUnit = { fg = p.crimson },
    CmpItemKindValue = { fg = p.crimson },
    CmpItemKindVariable = { fg = p.fg },
    CmpItemMenu = { fg = p.cmt },

    -- Blink (blink.cmp)
    BlinkCmpLabel = { fg = p.fg },
    BlinkCmpLabelDeprecated = { fg = p.cmt, strikethrough = true },
    BlinkCmpLabelMatch = { fg = p.orange, bold = true },
    BlinkCmpKind = { fg = p.teal },
    BlinkCmpKindClass = { fg = p.darkOrange },
    BlinkCmpKindColor = { fg = p.orange },
    BlinkCmpKindConstant = { fg = p.crimson },
    BlinkCmpKindConstructor = { fg = p.darkOrange },
    BlinkCmpKindEnum = { fg = p.darkOrange },
    BlinkCmpKindEnumMember = { fg = p.crimson },
    BlinkCmpKindEvent = { fg = p.teal },
    BlinkCmpKindField = { fg = p.teal },
    BlinkCmpKindFile = { fg = p.green },
    BlinkCmpKindFolder = { fg = p.brightGreen },
    BlinkCmpKindFunction = { fg = p.green },
    BlinkCmpKindInterface = { fg = p.darkOrange },
    BlinkCmpKindKeyword = { fg = p.brightGreen },
    BlinkCmpKindMethod = { fg = p.green },
    BlinkCmpKindModule = { fg = p.blueGreen },
    BlinkCmpKindOperator = { fg = p.blueGreen },
    BlinkCmpKindProperty = { fg = p.teal },
    BlinkCmpKindReference = { fg = p.crimson },
    BlinkCmpKindSnippet = { fg = p.darkYellow },
    BlinkCmpKindStruct = { fg = p.darkOrange },
    BlinkCmpKindText = { fg = p.fg },
    BlinkCmpKindTypeParameter = { fg = p.darkOrange },
    BlinkCmpKindUnit = { fg = p.crimson },
    BlinkCmpKindValue = { fg = p.crimson },
    BlinkCmpKindVariable = { fg = p.fg },
    BlinkCmpMenu = { fg = p.fg, bg = bg_float },
    BlinkCmpMenuBorder = { fg = p.teal, bg = bg_float },
    BlinkCmpMenuSelection = { fg = p.bg, bg = p.brightGreen },
    BlinkCmpDoc = { fg = p.fg, bg = bg_float },
    BlinkCmpDocBorder = { fg = p.teal, bg = bg_float },
    BlinkCmpDocSeparator = { fg = p.teal, bg = bg_float },
    BlinkCmpSignatureHelp = { fg = p.fg, bg = bg_float },
    BlinkCmpSignatureHelpBorder = { fg = p.teal, bg = bg_float },
    BlinkCmpGhostText = { fg = p.cmt },

    -- Notify (nvim-notify)
    NotifyERRORBorder = { fg = p.crimson },
    NotifyWARNBorder = { fg = p.darkOrange },
    NotifyINFOBorder = { fg = p.blueGreen },
    NotifyDEBUGBorder = { fg = p.cmt },
    NotifyTRACEBorder = { fg = p.blueGreen },
    NotifyERRORIcon = { fg = p.crimson },
    NotifyWARNIcon = { fg = p.darkOrange },
    NotifyINFOIcon = { fg = p.blueGreen },
    NotifyDEBUGIcon = { fg = p.cmt },
    NotifyTRACEIcon = { fg = p.blueGreen },
    NotifyERRORTitle = { fg = p.crimson },
    NotifyWARNTitle = { fg = p.darkOrange },
    NotifyINFOTitle = { fg = p.blueGreen },
    NotifyDEBUGTitle = { fg = p.cmt },
    NotifyTRACETitle = { fg = p.blueGreen },
    NotifyERRORBody = { fg = p.fg },
    NotifyWARNBody = { fg = p.fg },
    NotifyINFOBody = { fg = p.fg },
    NotifyDEBUGBody = { fg = p.fg },
    NotifyTRACEBody = { fg = p.fg },

    -- Noice
    NoiceCmdline = { fg = p.fg },
    NoiceCmdlineIcon = { fg = p.teal },
    NoiceCmdlineIconSearch = { fg = p.darkYellow },
    NoiceCmdlinePopup = { fg = p.fg, bg = bg_float },
    NoiceCmdlinePopupBorder = { fg = p.teal, bg = bg_float },
    NoiceCmdlinePopupTitle = { fg = p.brightGreen },
    NoiceCmdlinePrompt = { fg = p.brightGreen },
    NoiceConfirm = { fg = p.fg, bg = bg_float },
    NoiceConfirmBorder = { fg = p.teal, bg = bg_float },
    NoiceCursor = { fg = p.bg, bg = p.fg },
    NoiceFormatConfirm = { fg = p.brightGreen },
    NoiceFormatConfirmDefault = { fg = p.bg, bg = p.brightGreen },
    NoiceFormatDate = { fg = p.cmt },
    NoiceFormatEvent = { fg = p.teal },
    NoiceFormatKind = { fg = p.teal },
    NoiceFormatLevelDebug = { fg = p.cmt },
    NoiceFormatLevelError = { fg = p.crimson },
    NoiceFormatLevelInfo = { fg = p.blueGreen },
    NoiceFormatLevelOff = { fg = p.cmt },
    NoiceFormatLevelTrace = { fg = p.blueGreen },
    NoiceFormatLevelWarn = { fg = p.darkOrange },
    NoiceFormatProgressDone = { fg = p.bg, bg = p.brightGreen },
    NoiceFormatProgressTodo = { fg = p.fg, bg = p.lightBlack },
    NoiceFormatTitle = { fg = p.brightGreen },
    NoiceLspProgressClient = { fg = p.teal },
    NoiceLspProgressSpinner = { fg = p.brightGreen },
    NoiceLspProgressTitle = { fg = p.fg },
    NoiceMini = { fg = p.fg, bg = bg },
    NoicePopup = { fg = p.fg, bg = bg_float },
    NoicePopupBorder = { fg = p.teal, bg = bg_float },
    NoiceScrollbar = { bg = p.lightBlack },
    NoiceScrollbarThumb = { bg = p.punc },
    NoiceSplit = { fg = p.fg, bg = bg },
    NoiceSplitBorder = { fg = p.teal, bg = bg },
    NoiceVirtualText = { fg = p.teal },

    -- Trouble
    TroubleNormal = { fg = p.fg, bg = bg },
    TroubleCount = { fg = p.bg, bg = p.brightGreen, bold = true },
    TroubleText = { fg = p.fg },
    TroublePreview = { bg = p.selection },
    TroubleSource = { fg = p.cmt },
    TroubleCode = { fg = p.cmt },
    TroublePos = { fg = p.cmt },
    TroubleLocation = { fg = p.cmt },
    TroubleIndent = { fg = p.indentScope },
    TroubleFoldIcon = { fg = p.teal },
    TroubleFilename = { fg = p.brightGreen },
    TroubleIndentFoldClosed = { fg = p.fg },
    TroubleSignError = { fg = p.crimson },
    TroubleSignWarning = { fg = p.darkOrange },
    TroubleSignInformation = { fg = p.blueGreen },
    TroubleSignHint = { fg = p.teal },

    -- Flash
    FlashBackdrop = { fg = p.cmt },
    FlashMatch = { fg = p.fg, bg = p.selection },
    FlashCurrent = { fg = p.fg, bg = p.lightBlack },
    FlashLabel = { fg = p.bg, bg = p.orange, bold = true },
    FlashCursor = { link = "Cursor" },

    -- Leap
    LeapMatch = { fg = p.fg, bg = p.selection, bold = true },
    LeapLabelPrimary = { fg = p.bg, bg = p.orange, bold = true },
    LeapLabelSecondary = { fg = p.bg, bg = p.teal, bold = true },
    LeapBackdrop = { fg = p.cmt },

    -- Mini
    MiniCompletionActiveParameter = { underline = true },
    MiniCursorword = { bg = p.selection },
    MiniCursorwordCurrent = { bg = p.selection },
    MiniIndentscopeSymbol = { fg = p.teal },
    MiniIndentscopePrefix = { nocombine = true },
    MiniJump = { fg = p.bg, bg = p.orange },
    MiniJump2dSpot = { fg = p.orange, bold = true },
    MiniStarterCurrent = {},
    MiniStarterFooter = { fg = p.cmt },
    MiniStarterHeader = { fg = p.brightGreen },
    MiniStarterInactive = { fg = p.cmt },
    MiniStarterItem = { fg = p.fg },
    MiniStarterItemBullet = { fg = p.punc },
    MiniStarterItemPrefix = { fg = p.darkYellow },
    MiniStarterSection = { fg = p.teal },
    MiniStarterQuery = { fg = p.orange },
    MiniStatuslineDevinfo = { fg = p.altfg, bg = p.selection },
    MiniStatuslineFileinfo = { fg = p.altfg, bg = p.selection },
    MiniStatuslineFilename = { fg = p.altfg, bg = p.lightBlack },
    MiniStatuslineInactive = { fg = p.cmt, bg = p.lightBlack },
    MiniStatuslineModeCommand = { fg = p.bg, bg = p.darkYellow, bold = true },
    MiniStatuslineModeInsert = { fg = p.bg, bg = p.brightGreen, bold = true },
    MiniStatuslineModeNormal = { fg = p.bg, bg = p.green, bold = true },
    MiniStatuslineModeOther = { fg = p.bg, bg = p.blueGreen, bold = true },
    MiniStatuslineModeReplace = { fg = p.bg, bg = p.crimson, bold = true },
    MiniStatuslineModeVisual = { fg = p.bg, bg = p.orange, bold = true },
    MiniSurround = { fg = p.bg, bg = p.orange },
    MiniTablineCurrent = { fg = p.fg, bg = p.bg, bold = true },
    MiniTablineFill = { bg = p.lightBlack },
    MiniTablineHidden = { fg = p.altfg, bg = p.lightBlack },
    MiniTablineModifiedCurrent = { fg = p.darkYellow, bg = p.bg },
    MiniTablineModifiedHidden = { fg = p.darkYellow, bg = p.lightBlack },
    MiniTablineModifiedVisible = { fg = p.darkYellow, bg = p.lightBlack },
    MiniTablineTabpagesection = { fg = p.fg, bg = p.selection },
    MiniTablineVisible = { fg = p.altfg, bg = p.lightBlack },
    MiniTestEmphasis = { bold = true },
    MiniTestFail = { fg = p.crimson, bold = true },
    MiniTestPass = { fg = p.green, bold = true },
    MiniTrailspace = { bg = p.crimson },

    -- Nvim-navic
    NavicIconsFile = { fg = p.fg },
    NavicIconsModule = { fg = p.blueGreen },
    NavicIconsNamespace = { fg = p.blueGreen },
    NavicIconsPackage = { fg = p.blueGreen },
    NavicIconsClass = { fg = p.darkOrange },
    NavicIconsMethod = { fg = p.green },
    NavicIconsProperty = { fg = p.teal },
    NavicIconsField = { fg = p.teal },
    NavicIconsConstructor = { fg = p.darkOrange },
    NavicIconsEnum = { fg = p.darkOrange },
    NavicIconsInterface = { fg = p.darkOrange },
    NavicIconsFunction = { fg = p.green },
    NavicIconsVariable = { fg = p.fg },
    NavicIconsConstant = { fg = p.crimson },
    NavicIconsString = { fg = p.darkYellow },
    NavicIconsNumber = { fg = p.crimson },
    NavicIconsBoolean = { fg = p.crimson },
    NavicIconsArray = { fg = p.teal },
    NavicIconsObject = { fg = p.teal },
    NavicIconsKey = { fg = p.brightGreen },
    NavicIconsNull = { fg = p.crimson },
    NavicIconsEnumMember = { fg = p.crimson },
    NavicIconsStruct = { fg = p.darkOrange },
    NavicIconsEvent = { fg = p.teal },
    NavicIconsOperator = { fg = p.blueGreen },
    NavicIconsTypeParameter = { fg = p.darkOrange },
    NavicText = { fg = p.fg },
    NavicSeparator = { fg = p.cmt },

    -- Bufferline
    -- Note: bufferline dynamically creates DevIcon highlight groups
    -- We use NONE for inactive backgrounds to let it inherit properly
    BufferLineFill = { bg = p.bg },
    BufferLineBackground = { fg = p.cmt, bg = p.bg },
    BufferLineBuffer = { fg = p.cmt, bg = p.bg },
    BufferLineBufferVisible = { fg = p.altfg, bg = p.bg },
    BufferLineBufferSelected = { fg = p.fg, bg = p.bg, bold = true },
    BufferLineTab = { fg = p.cmt, bg = p.bg },
    BufferLineTabSelected = { fg = p.brightGreen, bg = p.bg, bold = true },
    BufferLineTabClose = { fg = p.cmt, bg = p.bg },
    BufferLineTabSeparator = { fg = p.bg, bg = p.bg },
    BufferLineTabSeparatorSelected = { fg = p.bg, bg = p.bg },
    BufferLineIndicatorSelected = { fg = p.brightGreen, bg = p.bg },
    BufferLineIndicatorVisible = { fg = p.bg, bg = p.bg },
    BufferLineSeparator = { fg = p.bg, bg = p.bg },
    BufferLineSeparatorVisible = { fg = p.bg, bg = p.bg },
    BufferLineSeparatorSelected = { fg = p.bg, bg = p.bg },
    BufferLineCloseButton = { fg = p.cmt, bg = p.bg },
    BufferLineCloseButtonVisible = { fg = p.altfg, bg = p.bg },
    BufferLineCloseButtonSelected = { fg = p.crimson, bg = p.bg },
    BufferLineModified = { fg = p.darkYellow, bg = p.bg },
    BufferLineModifiedVisible = { fg = p.darkYellow, bg = p.bg },
    BufferLineModifiedSelected = { fg = p.green, bg = p.bg },
    BufferLineDuplicate = { fg = p.cmt, bg = p.bg },
    BufferLineDuplicateVisible = { fg = p.altfg, bg = p.bg },
    BufferLineDuplicateSelected = { fg = p.altfg, bg = p.bg },
    BufferLinePick = { fg = p.orange, bg = p.bg, bold = true },
    BufferLinePickVisible = { fg = p.orange, bg = p.bg, bold = true },
    BufferLinePickSelected = { fg = p.orange, bg = p.bg, bold = true },
    BufferLineDiagnostic = { fg = p.cmt, bg = p.bg },
    BufferLineDiagnosticVisible = { fg = p.cmt, bg = p.bg },
    BufferLineDiagnosticSelected = { fg = p.altfg, bg = p.bg },
    BufferLineError = { fg = p.crimson, bg = p.bg },
    BufferLineErrorVisible = { fg = p.crimson, bg = p.bg },
    BufferLineErrorSelected = { fg = p.crimson, bg = p.bg },
    BufferLineErrorDiagnostic = { fg = p.crimson, bg = p.bg },
    BufferLineErrorDiagnosticVisible = { fg = p.crimson, bg = p.bg },
    BufferLineErrorDiagnosticSelected = { fg = p.crimson, bg = p.bg },
    BufferLineWarning = { fg = p.darkOrange, bg = p.bg },
    BufferLineWarningVisible = { fg = p.darkOrange, bg = p.bg },
    BufferLineWarningSelected = { fg = p.darkOrange, bg = p.bg },
    BufferLineWarningDiagnostic = { fg = p.darkOrange, bg = p.bg },
    BufferLineWarningDiagnosticVisible = { fg = p.darkOrange, bg = p.bg },
    BufferLineWarningDiagnosticSelected = { fg = p.darkOrange, bg = p.bg },
    BufferLineInfo = { fg = p.blueGreen, bg = p.bg },
    BufferLineInfoVisible = { fg = p.blueGreen, bg = p.bg },
    BufferLineInfoSelected = { fg = p.blueGreen, bg = p.bg },
    BufferLineInfoDiagnostic = { fg = p.blueGreen, bg = p.bg },
    BufferLineInfoDiagnosticVisible = { fg = p.blueGreen, bg = p.bg },
    BufferLineInfoDiagnosticSelected = { fg = p.blueGreen, bg = p.bg },
    BufferLineHint = { fg = p.teal, bg = p.bg },
    BufferLineHintVisible = { fg = p.teal, bg = p.bg },
    BufferLineHintSelected = { fg = p.teal, bg = p.bg },
    BufferLineHintDiagnostic = { fg = p.teal, bg = p.bg },
    BufferLineHintDiagnosticVisible = { fg = p.teal, bg = p.bg },
    BufferLineHintDiagnosticSelected = { fg = p.teal, bg = p.bg },
    BufferLineNumbers = { fg = p.cmt, bg = p.bg },
    BufferLineNumbersVisible = { fg = p.altfg, bg = p.bg },
    BufferLineNumbersSelected = { fg = p.brightGreen, bg = p.bg, bold = true },
    BufferLineGroupSeparator = { fg = p.cmt, bg = p.bg },
    BufferLineGroupLabel = { fg = p.bg, bg = p.brightGreen, bold = true },
    BufferLineOffsetSeparator = { fg = p.punc, bg = p.bg },
    BufferLineTruncMarker = { fg = p.cmt, bg = p.bg },
    -- DevIcon backgrounds (bufferline needs explicit icon highlight groups)
    BufferLineDevIconDefault = { bg = p.bg },
    BufferLineDevIconDefaultSelected = { bg = p.bg },
    BufferLineDevIconDefaultInactive = { bg = p.bg },
    -- Common file type icons
    BufferLineDevIconLua = { bg = p.bg },
    BufferLineDevIconLuaSelected = { bg = p.bg },
    BufferLineDevIconLuaInactive = { bg = p.bg },
    BufferLineDevIconVim = { bg = p.bg },
    BufferLineDevIconVimSelected = { bg = p.bg },
    BufferLineDevIconVimInactive = { bg = p.bg },
    BufferLineDevIconJs = { bg = p.bg },
    BufferLineDevIconJsSelected = { bg = p.bg },
    BufferLineDevIconJsInactive = { bg = p.bg },
    BufferLineDevIconTs = { bg = p.bg },
    BufferLineDevIconTsSelected = { bg = p.bg },
    BufferLineDevIconTsInactive = { bg = p.bg },
    BufferLineDevIconJson = { bg = p.bg },
    BufferLineDevIconJsonSelected = { bg = p.bg },
    BufferLineDevIconJsonInactive = { bg = p.bg },
    BufferLineDevIconMd = { bg = p.bg },
    BufferLineDevIconMdSelected = { bg = p.bg },
    BufferLineDevIconMdInactive = { bg = p.bg },
    BufferLineDevIconYml = { bg = p.bg },
    BufferLineDevIconYmlSelected = { bg = p.bg },
    BufferLineDevIconYmlInactive = { bg = p.bg },
    BufferLineDevIconToml = { bg = p.bg },
    BufferLineDevIconTomlSelected = { bg = p.bg },
    BufferLineDevIconTomlInactive = { bg = p.bg },
    BufferLineDevIconGitIgnore = { bg = p.bg },
    BufferLineDevIconGitIgnoreSelected = { bg = p.bg },
    BufferLineDevIconGitIgnoreInactive = { bg = p.bg },
    BufferLineDevIconPy = { bg = p.bg },
    BufferLineDevIconPySelected = { bg = p.bg },
    BufferLineDevIconPyInactive = { bg = p.bg },
    BufferLineDevIconRb = { bg = p.bg },
    BufferLineDevIconRbSelected = { bg = p.bg },
    BufferLineDevIconRbInactive = { bg = p.bg },
    BufferLineDevIconGo = { bg = p.bg },
    BufferLineDevIconGoSelected = { bg = p.bg },
    BufferLineDevIconGoInactive = { bg = p.bg },
    BufferLineDevIconRs = { bg = p.bg },
    BufferLineDevIconRsSelected = { bg = p.bg },
    BufferLineDevIconRsInactive = { bg = p.bg },
    BufferLineDevIconPhp = { bg = p.bg },
    BufferLineDevIconPhpSelected = { bg = p.bg },
    BufferLineDevIconPhpInactive = { bg = p.bg },
    BufferLineDevIconHtml = { bg = p.bg },
    BufferLineDevIconHtmlSelected = { bg = p.bg },
    BufferLineDevIconHtmlInactive = { bg = p.bg },
    BufferLineDevIconCss = { bg = p.bg },
    BufferLineDevIconCssSelected = { bg = p.bg },
    BufferLineDevIconCssInactive = { bg = p.bg },
    BufferLineDevIconScss = { bg = p.bg },
    BufferLineDevIconScssSelected = { bg = p.bg },
    BufferLineDevIconScssInactive = { bg = p.bg },
    BufferLineDevIconSh = { bg = p.bg },
    BufferLineDevIconShSelected = { bg = p.bg },
    BufferLineDevIconShInactive = { bg = p.bg },
    BufferLineDevIconZsh = { bg = p.bg },
    BufferLineDevIconZshSelected = { bg = p.bg },
    BufferLineDevIconZshInactive = { bg = p.bg },
    BufferLineDevIconC = { bg = p.bg },
    BufferLineDevIconCSelected = { bg = p.bg },
    BufferLineDevIconCInactive = { bg = p.bg },
    BufferLineDevIconCpp = { bg = p.bg },
    BufferLineDevIconCppSelected = { bg = p.bg },
    BufferLineDevIconCppInactive = { bg = p.bg },
    BufferLineDevIconH = { bg = p.bg },
    BufferLineDevIconHSelected = { bg = p.bg },
    BufferLineDevIconHInactive = { bg = p.bg },
    BufferLineDevIconHpp = { bg = p.bg },
    BufferLineDevIconHppSelected = { bg = p.bg },
    BufferLineDevIconHppInactive = { bg = p.bg },
    BufferLineDevIconJava = { bg = p.bg },
    BufferLineDevIconJavaSelected = { bg = p.bg },
    BufferLineDevIconJavaInactive = { bg = p.bg },
    BufferLineDevIconSql = { bg = p.bg },
    BufferLineDevIconSqlSelected = { bg = p.bg },
    BufferLineDevIconSqlInactive = { bg = p.bg },
    BufferLineDevIconDockerfile = { bg = p.bg },
    BufferLineDevIconDockerfileSelected = { bg = p.bg },
    BufferLineDevIconDockerfileInactive = { bg = p.bg },
    BufferLineDevIconMakefile = { bg = p.bg },
    BufferLineDevIconMakefileSelected = { bg = p.bg },
    BufferLineDevIconMakefileInactive = { bg = p.bg },
    BufferLineDevIconTxt = { bg = p.bg },
    BufferLineDevIconTxtSelected = { bg = p.bg },
    BufferLineDevIconTxtInactive = { bg = p.bg },
    BufferLineDevIconLicense = { bg = p.bg },
    BufferLineDevIconLicenseSelected = { bg = p.bg },
    BufferLineDevIconLicenseInactive = { bg = p.bg },

    -- Dashboard
    DashboardHeader = { fg = p.brightGreen },
    DashboardCenter = { fg = p.teal },
    DashboardFooter = { fg = p.cmt },
    DashboardShortCut = { fg = p.darkYellow },

    -- Alpha
    AlphaHeader = { fg = p.brightGreen },
    AlphaButtons = { fg = p.teal },
    AlphaShortcut = { fg = p.darkYellow },
    AlphaFooter = { fg = p.cmt },

    -- Snacks
    SnacksNormal = { fg = p.fg, bg = bg_float },
    SnacksDashboardNormal = { fg = p.fg, bg = bg },
    SnacksDashboardDesc = { fg = p.teal },
    SnacksDashboardFile = { fg = p.altfg },
    SnacksDashboardDir = { fg = p.cmt },
    SnacksDashboardFooter = { fg = p.cmt },
    SnacksDashboardHeader = { fg = p.brightGreen },
    SnacksDashboardIcon = { fg = p.brightGreen },
    SnacksDashboardKey = { fg = p.orange, bold = true },
    SnacksDashboardSpecial = { fg = p.brightGreen },
    SnacksDashboardTitle = { fg = p.brightGreen, bold = true },
    SnacksNotifierError = { fg = p.crimson },
    SnacksNotifierWarn = { fg = p.darkOrange },
    SnacksNotifierInfo = { fg = p.blueGreen },
    SnacksNotifierDebug = { fg = p.cmt },
    SnacksNotifierTrace = { fg = p.blueGreen },
    SnacksNotifierIconError = { fg = p.crimson },
    SnacksNotifierIconWarn = { fg = p.darkOrange },
    SnacksNotifierIconInfo = { fg = p.blueGreen },
    SnacksNotifierIconDebug = { fg = p.cmt },
    SnacksNotifierIconTrace = { fg = p.blueGreen },
    SnacksNotifierTitleError = { fg = p.crimson },
    SnacksNotifierTitleWarn = { fg = p.darkOrange },
    SnacksNotifierTitleInfo = { fg = p.blueGreen },
    SnacksNotifierTitleDebug = { fg = p.cmt },
    SnacksNotifierTitleTrace = { fg = p.blueGreen },
    SnacksNotifierBorderError = { fg = p.crimson },
    SnacksNotifierBorderWarn = { fg = p.darkOrange },
    SnacksNotifierBorderInfo = { fg = p.blueGreen },
    SnacksNotifierBorderDebug = { fg = p.cmt },
    SnacksNotifierBorderTrace = { fg = p.blueGreen },
    SnacksIndent = { fg = p.indentScope },
    SnacksIndentScope = { fg = p.teal },
    SnacksPickerMatch = { fg = p.orange, bold = true },
    SnacksPickerPrompt = { fg = p.brightGreen },
    SnacksPickerDir = { fg = p.cmt },
    SnacksPickerFile = { fg = p.fg },
    SnacksPickerDirectory = { fg = p.brightGreen },
    SnacksPickerTitle = { fg = p.brightGreen, bold = true },
    SnacksPickerBorder = { fg = p.teal },
    SnacksPickerSelection = { bg = p.selection },
    SnacksPickerSelectionCaret = { fg = p.orange, bg = p.selection },
    SnacksInputIcon = { fg = p.brightGreen },
    SnacksInputBorder = { fg = p.teal },
    SnacksInputTitle = { fg = p.brightGreen },
    SnacksDim = { fg = p.cmt },
    SnacksScratchKey = { fg = p.orange },
    SnacksScratchDesc = { fg = p.teal },
    SnacksProfilerIconInfo = { fg = p.blueGreen },
    SnacksProfilerBadge = { fg = p.bg, bg = p.teal },
  }
end

return { get = get }
